### ISSUE TITLE
HALEM with ROMS model in simple setup

### ISSUE THREAD

**Issue by ivicajan** [Pietervanhalem/Personal-Code-Examples#1]
Hi Pieter,
I am trying to use HALEM to optimize swim route using ROMS ocean currents ;)
To do that I wrote class flow_ROMS that is reading model nodes, currents etc from the opendap roms server taking into account mask.
All looks fine, structure etc, till the actual optimization part where it is not working. I think I have more/less reading and pre-processing right. 
From the swimming optimization I do not need all functionality of halem, so wondering if it is possible to disable those computations (i.e. under keel clearance, vessel draft etc.). I put them to something but sill complaining about computations and overflow.

Any comment is more than welcome! Thanks for your time in advance.
Attached is example I tried.
Regards,
Ivica

[test_ROMS.txt](https://github.com/Pietervanhalem/Personal-Code-Examples/files/4297015/test_ROMS.txt)

**Comment by Pietervanhalem** [comment]
issue moved to the HALEM repo see [HALEM issue 8](https://github.com/TUDelft-CITG/HALEM/issues/8)
